---
- id: root
  options:
    - id: blog
      type: document_type
    - id: news
      type: document_type_selection
    - id: guidance_and_regulation
      type: document_type_selection
    - id: transparency_statistics_reports
      type: document_type_selection
    - id: policy
      type: document_type_selection
    - id: specialist_notices
      type: document_type_selection
    - id: not_sure
      type: managed_elsewhere
      path: /documents/publishing-guidance

- id: guidance_publications
  options:
    - id: detailed_guide
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/detailed-guides/new
    - id: guidance
      type: document_type
    - id: guidance_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: statutory_guidance
      type: document_type
    - id: statutory_guidance_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: manual
      type: managed_elsewhere
      hostname: support
      path: /content_advice_request/new
    - id: any_mainstream_publication
      type: managed_elsewhere
      hostname: support
      path: /content_change_request/new

- id: guidance_and_regulation
  options:
    - id: guidance_publications
      type: document_type_selection
    - id: form
      type: document_type
    - id: form_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: regulation
      type: document_type
    - id: regulation_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: map
      type: document_type
    - id: map_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new

- id: news
  options:
    - id: news_story
      type: document_type
    - id: press_release
      type: document_type
    - id: speech
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/speeches/new
    - id: statement_to_parliament
      type: document_type_selection
    - id: case_study
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/case-studies/new
    - id: authored_article
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/speeches/new

- id: policy
  options:
    - id: impact_assessment
      type: document_type
    - id: impact_assessment_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: consultation
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/consultations/new
    - id: policy_paper
      type: document_type
    - id: policy_paper_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new

- id: specialist_notices
  options:
    - id: notice
      type: document_type
    - id: notice_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: decision
      type: document_type
    - id: decision_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: specialist_notice
      type: managed_elsewhere
      hostname: specialist-publisher
      path: /
    - id: fatality_notice
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/fatalities/new

- id: statement_to_parliament
  options:
    - id: written_statement
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/speeches/new
    - id: oral_statement
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/speeches/new

- id: statistics
  options:
    - id: official_statistics
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: national_statistics
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: statistics_announcement
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/statistics_announcements/new
    - id: statistical_dataset
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/statistical-data-sets/new

- id: transparency_statistics_reports
  options:
    - id: statistics
      type: document_type_selection
    - id: transparency
      type: document_type
    - id: transparency_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: corporate_report
      type: document_type
    - id: corporate_report_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: research
      type: document_type
    - id: research_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: correspondence
      type: document_type
    - id: correspondence_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: foi_release
      type: document_type
    - id: foi_release_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: independent_report
      type: document_type
    - id: independent_report_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: international_treaty
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
    - id: promotional
      type: document_type
    - id: promotional_managed_elsewhere
      type: managed_elsewhere
      hostname: whitehall-admin
      path: /government/admin/publications/new
